Users:
  - Beata
  - Marta

Beata:
  - 0 # index of column of worksheet

Marta:
  - 3 # index of column of worksheet

dict_time_break: 2 # in seconds; break between English word and translation

columnNames: ['week','data','Beata','tłumaczenie','t1','Marta','tłumaczenie','t2']

Xlsx:
  sheet_name: 'GRA'
  DOCUMENT_ID: '1De721tDfHyQ_ea1VPlKoK5cEt-3AJtx9SxX2b8PrVOc'
  WORKSHEET_SLOWKA_ID: '215234428'
  WORKSHEET_ZDANIA_ID: '1837591233'
  WORKSHEET_SLOWKA_NAME: 'slowka'
  WORKSHEET_ZDANIA_NAME: 'zdania'
