Users:
  - Beata
  - Marta


Beata:
  - 0 # index of column of worksheet

Marta:
  - 4 # index of column of worksheet

dictionaryBreak: 2 # in seconds

columnNames: ['week','data','Beata','tłumaczenie','t1','Marta','tłumaczenie','t2']

GcpConnect:
    # Ścieżka do pliku JSON z kluczami dostępu
  credentials_file: 'secrets/angwithmarta.json'
    # Zakres uprawnień
  scope: ['https://spreadsheets.google.com/feeds', 'https://www.googleapis.com/auth/drive']

Xlsx:
  sheet_name: 'Gra w słówka'